<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
    <name>pilla_teleop</name>
    <version>0.6.2</version>
    <description>Gamepad teleop node for Pilla Robot.</description>

    <maintainer email="vish@wychar.com">Vishwajeet Narwal</maintainer>

    <license>BSD</license>

    <url type="website"></url>

    <author>Vishwajeet Narwal</author>

    <buildtool_depend>ament_cmake</buildtool_depend>

    <exec_depend>champ_msgs</exec_depend>
    <exec_depend>geometry_msgs</exec_depend>
    <exec_depend>joy</exec_depend>
    <exec_depend>rclpy</exec_depend>
    <exec_depend>sensor_msgs</exec_depend>

    <export>
        <build_type>ament_cmake</build_type>
    </export>
</package>
