<?xml version="1.0"?>
<package>
    <name>pilla_teleop</name>
    <version>0.6.2</version>
    <description>Gamepad teleop node for Pilla Robot.</description>

    <maintainer email="vish@wychar.com">Vishwajeet Narwal</maintainer>

    <license>BSD</license>

    <url type="website"></url>

    <author>Vishwajeet Narwal</author>


    <buildtool_depend>ament_cmake</buildtool_depend>

    <run_depend>geometry_msgs</run_depend>
    <run_depend>joy</run_depend>
    <run_depend>rclpy</run_depend>
    <run_depend>sensor_msgs</run_depend>

    <export>
        <build_type>ament_cmake</build_type>
    </export>
</package>
