version: '2'

networks:
  ros:
    driver: bridge

services:
  ros-master:
    image: ros:melodic-ros-core
    command: stdbuf -o L roscore
    networks:
      - ros
    restart: always


  talker:
    image: ros:melodic-ros-core
    depends_on:
      - ros-master
    environment:
      - "ROS_MASTER_URI=http://ros-master:11311"
      - "ROS_HOSTNAME=talker"
    command: stdbuf -o L rostopic pub /chatter std_msgs/String "hello" -r 1
    networks:
      - ros
    restart: always

  listener:
    image: ros:melodic-ros-core
    depends_on:
      - ros-master
    environment:
      - "ROS_MASTER_URI=http://ros-master:11311"
      - "ROS_HOSTNAME=listener"
    command: stdbuf -o L rostopic hz /chatter
    networks:
      - ros
    restart: always

  ros-bridge-server:
    build:
      context: ./champ
      dockerfile: dockerfile
    depends_on:
      - ros-master
    environment:
      - "ROS_MASTER_URI=http://ros-master:11311"
      - "ROS_HOSTNAME=ros-bridge-server"
    volumes:
      - ./champ/ros_ws:/home/ros_ws
    networks:
      - ros
    ports:
      - "9090:9090"
    command: /bin/bash -c "source /home/ros_ws/devel/setup.bash && roslaunch rosbridge_server rosbridge_websocket.launch"
    restart: always

  pilla-can-control:
    build:
      context: ./can_control
      dockerfile: dockerfile
    depends_on:
      - ros-bridge-server
    volumes:
      - ./can_control/src:/home/src
    networks:
      - ros
    command: /bin/bash -c "python3 champ_ws.py"
    restart: always

  # pilla-champ-controller:
  #   build:
  #     context: ./champ
  #     dockerfile: dockerfile
  #   depends_on:
  #     - ros-master
  #   environment:
  #     - "ROS_MASTER_URI=http://ros-master:11311"
  #     - "ROS_HOSTNAME=listener"
  #   volumes:
  #   - ./ros_ws:/home/ros_ws
  #   networks:
  #     - ros
  #   command: /bin/bash -c "roslaunch champ_config bringup.launch"
  #   restart: always

  # pilla-champ-teleop:
  #   build:
  #     context: ./champ
  #     dockerfile: dockerfile
  #   depends_on:
  #     - ros-master
  #   environment:
  #     - "ROS_MASTER_URI=http://ros-master:11311"
  #     - "ROS_HOSTNAME=listener"
  #   volumes:
  #   - ./ros_ws:/home/ros_ws
  #   networks:
  #     - ros
  #   command: /bin/bash -c "roslaunch champ_teleop teleop.launch"
  #   restart: always