
def set_power_related_settings(odrv0):
    """
    Set power-related settings for the ODrive motor controller.
    This includes setting limits for current, velocity, and other key hardware parameters.
    """
    
    # Setting Limits for safekeeping of motor and driver

    ### Current

    odrv0.axis0.motor.config.current_lim = 30

    # The above command sets the current threshold to 30A. Note that this current threshold refers to the Q-axis current, not the supply current.
    # This threshold directly limits the output torque. For 6010-8, please do not set this threshold above 50A!

    ### Velocity Limit
    odrv0.axis0.controller.config.enable_vel_limit = 1
    odrv0.axis0.controller.config.vel_limit = 30

    # The system has a global speed limit, which is limited to 30 turn/s (revolutions per second). Note that pure moment is the default rule.
    # This speed limit does not work in mode, but can be enabled by turning on the switch described below

    odrv0.axis0.controller.config.enable_torque_mode_vel_limit = 1


    ### Calibrate Current
    # This current is 5A by default, which does not need to be modified by default, but if the user's supply current is small, this value can be reduced, otherwise a low voltage alarm will appear during calibration.

    odrv0.axis0.motor.config.calibration_current = 5


    ##  Set key hardware parameters

    ###  Maximum discharge/charge current

    # The discharge current refers to the forward current that the power supply supplies to the driver and motor, and the charging current refers to the current flowing into the power supply in the opposite direction. Both
    # The value is related to the power supply, please set it to an appropriate value to avoid the voltage being pulled down due to the power supply being unable to discharge, or being back electromotive damage. Note, however, that if you set these two values to a value with a small absolute value, it is easy to generate an alarm

    odrv0.config.dc_max_negative_current = -1
    odrv0.config.dc_max_positive_current = 30

def set_motor_related_settings(odrv0):
    ###  Number of pole pairs
    # The number of pole pairs is the number of poles in the rotor of the motor divided by 2. The user must set this value correctly for the calibration to be successful, otherwise it will cause a calibration alarm.

    odrv0.axis0.motor.config.pole_pairs = 14

    ### Torque Constant
    # The torque constant is the torque generated by the motor divided by the Q-axis current, and its relationship with the Kv value of the motor is : 8.27.

    odrv0.axis0.motor.config.torque_constant = 0.47

    # Whether the torque constant is correct or not does not affect the operation of the motor, but it will affect the unit conversion of the value entered by the user when doing torque control.
    # If you want to control the moment in units A instead of Nm, simply set this value to 1.

def set_temperature_related_settings(odrv0):
    """
    Set temperature-related settings for the ODrive motor controller.
    This includes enabling temperature sensors and setting temperature limits for protection.
    """
    ### Temprature Sensing
    # Both the driver board and the motor are equipped with NTC temperature sensors, and if enabled, the driver controls the output current (torque) according to the temperature to protect the driver and the motor.

    #### Motor temperature protection
    odrv0.axis0.motor.motor_thermistor.config.enabled = 1
    odrv0.axis0.motor.motor_thermistor.config.temp_limit_lower = 20
    odrv0.axis0.motor.motor_thermistor.config.temp_limit_upper = 100

    ####  Driver board temperature protection
    odrv0.axis0.motor.fet_thermistor.config.enabled = 1
    odrv0.axis0.motor.fet_thermistor.config.temp_limit_lower = 20
    odrv0.axis0.motor.fet_thermistor.config.temp_limit_upper = 100

def set_pid_parameters(odrv0):
    """
    Set PID parameters for the ODrive motor controller.
    This includes setting position and velocity gains for the motor controller.
    """
    
    # Position and Velocity Control Gains
    # The default values are set to 20.0 for position gain, 0.16 for velocity gain, and 0.32 for velocity integrator gain.
    odrv0.axis0.controller.config.pos_gain=20.0
    odrv0.axis0.controller.config.vel_gain=0.16
    odrv0.axis0.controller.config.vel_integrator_gain=0.32



import odrive
import time

odrv0 = odrive.find_any()

set_power_related_settings(odrv0)
set_motor_related_settings(odrv0)
set_temperature_related_settings(odrv0)
set_pid_parameters(odrv0)

odrv0.save_configuration()




