FROM ubuntu:18.04

RUN apt-get update
RUN apt-get install -y curl gnupg2 lsb-release
RUN sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'
RUN curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | apt-key add -
RUN apt-get update
# Set timezone as US/Central
RUN ln -fs /usr/share/zoneinfo/America/Chicago /etc/localtime
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y tzdata
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y ros-melodic-desktop-full
# RUN rm -rf /var/lib/apt/lists/*

SHELL ["/bin/bash", "-c"]
RUN echo "source /opt/ros/melodic/setup.bash" >> ~/.bashrc

COPY ros_ws /home/ros_ws
WORKDIR /home/ros_ws

RUN mkdir -p src

WORKDIR /home/ros_ws

RUN apt install -y git python-rosdep python-rosinstall python-rosinstall-generator python-wstool build-essential

WORKDIR /home/ros_ws/src

RUN git clone --recursive https://github.com/chvmp/champ
RUN git clone https://github.com/chvmp/champ_teleop


WORKDIR /home/ros_ws


RUN rosdep init
RUN rosdep update

RUN rosdep install --from-paths src --ignore-src -r -y

RUN /bin/bash -c "source /opt/ros/melodic/setup.bash && catkin_make"


RUN apt install -y ros-melodic-rosbridge-server

RUN echo "source /home/ros_ws/devel/setup.bash" >> ~/.bashrc

EXPOSE 9090
# Entry point
ENTRYPOINT [ "/bin/bash", "-c", "source /opt/ros/melodic/setup.bash && source /home/ros_ws/devel/setup.bash"]
CMD [ "/bin/bash" ]
