FROM ubuntu:18.04

RUN apt-get update

RUN apt-get install -y python3 python3-dev build-essential

RUN apt-get install -y python3-pip

RUN pip3 install --upgrade pip

RUN pip3 install roslibpy cantools

COPY src /home/src

WORKDIR /home/src
